Fixed bug that wrong method was referenced when refresh rate was changed
Error message:
(gnome-shell:476603): Gjs-CRITICAL **: 23:17:28.030: JS ERROR:
TypeError: this._set_timeout is not a function
_init/<@file:///home/bernd/.local/share/gnome-shell/extensions/marcs14@gmail.com/extension.js:58:14
@resource:///org/gnome/shell/ui/init.js:21:20