Fix for issue #19, but beware - I changed a lot of code (#20)
* first working version to support multiple batteries

* no display when power=0, streamlined strings

* no display when power=0, streamlined strings

* Refactoring, improved error handling, supports BATT, supports currentnow+voltagenow

* Updated VSCode config

* Small refactorings

* More small refactorings

* Fixed bug that wrong method was referenced when refresh rate was changed

Error message:
(gnome-shell:476603): Gjs-CRITICAL **: 23:17:28.030: JS ERROR:
TypeError: this._set_timeout is not a function
_init/<@file:///home/bernd/.local/share/gnome-shell/extensions/marcs14@gmail.com/extension.js:58:14
@resource:///org/gnome/shell/ui/init.js:21:20

* Fixed bug where power consumption of 0.1 would not be displayed, refactoring

* Major change: finds all batteries, puts labels for BAT0, BAT1

* Just disabled debug logging

* Code to show 0W added, but no setting defined yet, some refactoring

* Code to show 0W added, but no setting defined yet, some refactoring

* Setting "showzeropower" implemented

* Added German translation for additional settings strings

* Updated README.md and CHANGELOG.md

* Code restructered to singel class, fixed settings bug

* Fix for duplicate minus sign on some hw, Fix for 0.1W display if charging finished

* Added functionality and setting to toggle debug logs

* changed default for showzeropower from false to true

* Fixed a few errors and updated README

* Update README.md

Fixed a newly introduced typo, removed other implemented feature from wishlist

---------

Co-authored-by: aProfessionalFrog <nikoh8408@gmail.com>